name: Secret and Variable Example Workflow

on: [push]

env:
  MY_VARIABLE: '${{ env.WEB_URL }}'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Print Variable
        run: echo "Variable is ${{ MY_VARIABLE }}"
