name: Variable Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: ${{ env.WEB_URL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print Variable
        run: echo "Variable is ${{ env.MY_VARIABLE }}"
