name: Example Workflow

on: [push]

env:
  MY_VARIABLE: '${{ env.WEB_URL }}'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Variable
        run: echo "Variable is ${{ env.MY_VARIABLE }}"
