name: Playwright Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    env:
      WEB_URL: ${{ secrets.WEB_URL }}
      EMAIL_LOCATOR: ${{ secrets.EMAIL_LOCATOR }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PASSWORD_LOCATOR: ${{ secrets.PASSWORD_LOCATOR }}
      SUBMIT: ${{ secrets.SUBMIT }}
      EMAIL: ${{ secrets.EMAIL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Check for focused tests (test.only / describe.only)
        run: |
          if grep -rnw './tests' -e '\.only('; then
            echo "❌ Found test.only or describe.only in test files. Please remove them before pushing."
            exit 1
          fi

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Notify Discord on Push
        if: github.event_name == 'push'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🚀 New code push to \`${{ github.ref_name }}\` by \`${{ github.actor }}\`\n🔗 https://github.com/${{ github.repository }}/commit/${{ github.sha }}\"}" \
          $DISCORD_WEBHOOK

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
